(()=>{'use strict';
const P=window.SISEBOM_PHONES||[],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],won=n=>Number.isFinite(Number(n))&&Number(n)>0?Math.round(Number(n)).toLocaleString('ko-KR')+'원':'-';
const ONLINE_API='https://sisebom.onrender.com',LOCAL_API='http://localhost:3000',API_BASE=['localhost','127.0.0.1'].includes(location.hostname)?LOCAL_API:ONLINE_API;
let current=P.find(x=>x.id==='iphone-15')||P[0],filters={platform:'all',storage:'all',min:null,max:null,sort:'cheap'},liveListings=[],liveState={loading:false,error:'',fetchedAt:'',providers:{}},requestSeq=0;
function norm(s){return String(s||'').toLowerCase().replace(/프로\s*맥스/g,'promax').replace(/프로/g,'pro').replace(/플러스/g,'plus').replace(/미니/g,'mini').replace(/에어/g,'air').replace(/에스\s*이/g,'se').replace(/\s+/g,'').replace(/gb/g,'').replace(/기가/g,'').replace(/-/g,'')}
function searchableAliases(p){return [p.name,...(p.aliases||[])].map(norm).filter(Boolean)}
function findPhone(q){let nq=norm(q);if(nq==='아이폰9'||nq==='iphone9')nq=norm('iPhone X');if(!nq)return current;let exact=P.find(p=>searchableAliases(p).some(a=>a===nq));if(exact)return exact;let best=null,bestScore=-Infinity;for(const p of P){for(const a of searchableAliases(p)){if(a==='iphone'||a==='아이폰')continue;let score=-Infinity;if(nq.includes(a))score=5000+a.length;else if(a.includes(nq))score=3000-(a.length-nq.length);if(score>bestScore){bestScore=score;best=p}}}return best||current}
function storageText(p){return (p.storage||[]).map(x=>x>=1024?(x/1024)+'TB':x+'GB').join(' · ')||'-'}
function setImage(p){const im=$('#productImage'),fb=$('#imageFallback');im.onerror=()=>{im.hidden=true;fb.hidden=false};im.src=p.image;im.hidden=false;fb.hidden=true}
function perfSub(p){const base=p.performance||50;return {daily:Math.min(100,base+3),game:Math.max(0,base-3),camera:Math.min(100,Math.max(20,base+(p.name.includes('Pro')?4:-4)))} }
function quantile(sorted,q){if(!sorted.length)return 0;const pos=(sorted.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);if(lo===hi)return sorted[lo];return sorted[lo]+(sorted[hi]-sorted[lo])*(pos-lo)}
function robustMarketStats(listings){const valid=listings.filter(x=>Number.isFinite(Number(x.price))&&Number(x.price)>0),prices=valid.map(x=>Number(x.price)).sort((a,b)=>a-b);if(!prices.length)return {count:0,usedCount:0,outlierCount:0,min:0,average:0,max:0,median:0,low:0,high:0,used:[]};let used=valid,low=prices[0],high=prices[prices.length-1];if(prices.length>=5){const q1=quantile(prices,.25),q3=quantile(prices,.75),iqr=q3-q1;if(iqr>0){low=Math.max(1000,q1-1.5*iqr);high=q3+1.5*iqr;const core=valid.filter(x=>Number(x.price)>=low&&Number(x.price)<=high);if(core.length>=Math.max(3,Math.ceil(valid.length*.6)))used=core}}const up=used.map(x=>Number(x.price)).sort((a,b)=>a-b),average=up.reduce((a,b)=>a+b,0)/up.length;return {count:valid.length,usedCount:used.length,outlierCount:valid.length-used.length,min:Math.min(...up),average,max:Math.max(...up),median:quantile(up,.5),low,high,used}}
function marketBuyScore(stats,p){if(!stats.usedCount)return 0;const median=stats.median||stats.average||1,spread=(stats.max-stats.min)/median;let score=52;const newPrice=Number(p?.newPrice)||0;if(newPrice>0){const discount=1-median/newPrice;score+=Math.max(-12,Math.min(24,discount*50))}else score+=5;score+=Math.min(10,stats.usedCount*1.25);score-=Math.min(16,Math.max(0,spread-.15)*18);score+=(Number(p?.performance||50)-50)*.08;return Math.max(1,Math.min(100,Math.round(score)))}
function htmlEscape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function buildListingQuery(p){return String(p?.name||'').replace(/^iPhone/i,'아이폰').replace(/Pro Max/ig,'프로맥스').replace(/Pro/ig,'프로').replace(/Plus/ig,'플러스').replace(/mini/ig,'미니').replace(/Air/ig,'에어').replace(/SE/ig,'SE')}function liveSearchQuery(){const base=buildListingQuery(current);if(filters.storage==='all')return base;const n=Number(filters.storage);return `${base} ${n>=1024?n/1024+'TB':n+'GB'}`}
function availableOnly(x){return !/(예약\s*중|판매\s*완료|거래\s*완료|판매종료|거래종료)/i.test(`${x?.status||''} ${x?.title||''}`)}
function filteredListings(){let a=liveListings.filter(availableOnly);if(filters.platform!=='all')a=a.filter(x=>x.platform===filters.platform);if(filters.storage!=='all')a=a.filter(x=>String(x.storage)===String(filters.storage));if(filters.min!=null)a=a.filter(x=>Number(x.price)>=filters.min);if(filters.max!=null)a=a.filter(x=>Number(x.price)<=filters.max);if(filters.sort==='cheap')a.sort((a,b)=>Number(a.price)-Number(b.price));if(filters.sort==='high')a.sort((a,b)=>Number(b.price)-Number(a.price));if(filters.sort==='new')a.sort((a,b)=>Number(a.minutes??999999)-Number(b.minutes??999999));return a}
function renderProduct(){const p=current,s=perfSub(p);$('#resultName').textContent=p.name;$('#productHeading').textContent=p.name+' 제품 정보';$('#specManufacturer').textContent=p.brand;$('#specChipset').textContent=p.chipset;$('#specDisplay').textContent=p.display;$('#specCamera').textContent=p.camera;$('#specCharging').textContent=p.charging;$('#specFrame').textContent=p.frame;$('#specStorage').textContent=storageText(p);$('#perfScore').textContent=p.performance;$('#dailyScore').textContent=s.daily;$('#gameScore').textContent=s.game;$('#cameraScore').textContent=s.camera;$('#dailyBar').style.width=s.daily+'%';$('#gameBar').style.width=s.game+'%';$('#cameraBar').style.width=s.camera+'%';setImage(p);document.title='시세봄 - '+p.name;renderStorage();renderCompare()}
function renderStorage(){const box=$('#storageFilters');box.innerHTML='<button class="chip '+(filters.storage==='all'?'active':'')+'" data-storage="all">전체</button>'+((current.storage||[]).map(s=>`<button class="chip ${String(filters.storage)===String(s)?'active':''}" data-storage="${s}">${s>=1024?s/1024+'TB':s+'GB'}</button>`).join(''));box.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const next=b.dataset.storage;if(String(filters.storage)===String(next))return;filters.storage=next;renderStorage();await loadLiveListings()})}
function renderMarket(){const arr=filteredListings(),stats=robustMarketStats(arr);$('#resultCount').textContent=arr.length;$('#visibleCount').textContent=arr.length;$('#minPrice').textContent=won(stats.min);$('#avgPrice').textContent=won(stats.average);$('#maxPrice').textContent=won(stats.max);$('#newPrice').textContent=current.newPrice?won(current.newPrice):'정보 없음';const note=$('#marketDataNote');if(note){if(!arr.length)note.textContent=liveState.loading?'실제 매물을 불러오는 중입니다.':'시세를 계산할 매물이 없습니다.';else note.textContent=`실제 판매중 매물 ${arr.length}개 중 ${stats.usedCount}개로 시세 계산${stats.outlierCount?` · 극단값 ${stats.outlierCount}개는 시세 계산에서만 제외`:''}`;}if(!stats.usedCount){$('#buyScore').textContent='-';$('#scoreCircle').className='score-circle';$('#buyBadge').className='buy-badge';$('#buyBadge').textContent=liveState.loading?'불러오는 중':'분석 대기';$('#aiHeadline').textContent=liveState.loading?'실제 매물 불러오는 중':liveState.error?'매물 불러오기 실패':'매물 없음';$('#aiText').textContent=liveState.loading?'당근·번개장터·중고나라 공개 검색 결과를 확인하고 있습니다.':liveState.error?liveState.error:'현재 조건에 맞는 판매중 매물이 없습니다.'}else{const score=marketBuyScore(stats,current),cls=score>=70?'green':score>=40?'yellow':'red',txt=score>=70?'구매하기 좋은 편':score>=40?'조금 더 비교':'구매 비추천',platformCount=new Set(arr.map(x=>x.platform).filter(Boolean)).size;$('#buyScore').textContent=score;$('#scoreCircle').className='score-circle '+cls;$('#buyBadge').className='buy-badge '+cls;$('#buyBadge').textContent=txt;$('#aiHeadline').textContent=txt;$('#aiText').textContent=`${current.name} 판매중 매물 ${arr.length}개를 ${platformCount||1}개 플랫폼에서 분석했습니다. ${stats.outlierCount?`비정상적으로 낮거나 높은 가격 ${stats.outlierCount}개를 시세 계산에서 제외하고 `:''}${stats.usedCount}개 기준 평균가는 ${won(stats.average)}입니다.`}$('#chartLabel').textContent=filters.storage==='all'?'전체 용량':(Number(filters.storage)>=1024?Number(filters.storage)/1024+'TB':filters.storage+'GB');renderBars(arr);renderListings(arr,stats)}
function renderBars(arr){if(!arr.length){$('#bars').innerHTML='<div class="muted listing-empty">표시할 가격 데이터가 없습니다.</div>';return}const ps=arr.map(x=>Number(x.price)).filter(Number.isFinite),mn=Math.min(...ps),mx=Math.max(...ps);$('#bars').innerHTML=arr.slice(0,24).map(x=>`<div class="bar-wrap"><div class="bar" style="height:${40+((Number(x.price)-mn)/(mx-mn||1))*150}px"></div><div class="bar-label">${Math.round(Number(x.price)/10000)}만</div></div>`).join('')}
function cleanListingTitle(x){let t=String(x?.title||'').replace(/^Title:\s*/i,'').replace(/\s+/g,' ').trim();t=t.replace(/\s*\|\s*디지털기기\s*\|\s*당근\s*중고거래.*$/i,'');t=t.replace(/\s*\|\s*중고나라\s*-\s*안심되는\s*중고거래.*$/i,'');if(x?.platform==='번개장터'){t=t.replace(/\s+상품상태\b[\s\S]*$/i,'').replace(/\s+제품정보\b[\s\S]*$/i,'')}if(t.length>72)t=t.slice(0,69).trimEnd()+'…';return t||`${x?.platform||'중고'} 매물`}
function listingMetaText(x){const bits=[];if(String(x?.region||'').trim())bits.push(String(x.region).trim());if(String(x?.timeText||'').trim())bits.push(String(x.timeText).trim());return bits.join(' · ')||'상세 정보는 원본에서 확인'}
function platformCountText(items){return ['당근','번개장터','중고나라'].map(name=>`${name} ${items.filter(x=>x.platform===name).length}개`).join(' · ')}
function renderListings(a,marketStats=robustMarketStats(a)){const grid=$('#listingGrid');if(liveState.loading){grid.innerHTML='<div class="listing-state"><b>당근·번개장터·중고나라 실제 매물 불러오는 중...</b><span>잠시만 기다려주세요.</span></div>';return}if(liveState.error&&!a.length){grid.innerHTML=`<div class="listing-state error"><b>매물을 불러오지 못했습니다.</b><span>${htmlEscape(liveState.error)}</span></div>`;return}if(!a.length){grid.innerHTML='<div class="listing-state"><b>조건에 맞는 판매중 매물이 없습니다.</b><span>예약중·판매완료·거래완료 매물은 표시하지 않습니다.</span></div>';return}const avg=marketStats.average||a.reduce((s,x)=>s+Number(x.price),0)/a.length;grid.innerHTML=a.map(x=>{const d=avg?(Number(x.price)-avg)/avg*100:0,dc=d<=-7?'good':d>=10?'bad':'',dt=d<=-7?`평균보다 ${Math.abs(d).toFixed(0)}% 저렴`:d>=10?`평균보다 ${d.toFixed(0)}% 비쌈`:'적정 시세',storage=x.storage?(x.storage>=1024?x.storage/1024+'TB':x.storage+'GB'):'용량 미표기',title=cleanListingTitle(x),meta=listingMetaText(x),img=x.image?`<img class="listing-image" src="${htmlEscape(x.image)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<div class="listing-image placeholder"><b>사진 없음</b><span>원본 매물에서 확인</span></div>';return `<article class="listing">${img}<div class="listing-body"><div class="listing-top"><span class="platform-badge">${htmlEscape(x.platform)}</span><span>${storage}</span></div><h3 title="${htmlEscape(title)}">${htmlEscape(title)}</h3><b class="listing-price">${won(x.price)}</b><div class="deal ${dc}">${dt}</div><div class="listing-meta"><span>${htmlEscape(meta)}</span><a href="${htmlEscape(x.url)}" target="_blank" rel="noopener noreferrer">원본 매물 보기 ↗</a></div></div></article>`}).join('')}
function renderCompare(){const sel=$('#compareSelect');if(!sel.options.length)sel.innerHTML=P.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');if(sel.value===current.id)sel.value=P.find(x=>x.id!==current.id)?.id||current.id;const b=P.find(x=>x.id===sel.value)||P[0];$('#compareAName').textContent=current.name;$('#compareAChip').textContent=current.chipset;$('#compareBChip').textContent=b.chipset;$('#compareADisplay').textContent=current.display;$('#compareBDisplay').textContent=b.display;$('#compareAPerf').textContent=current.performance;$('#compareBPerf').textContent=b.performance;$('#compareAStorage').textContent=storageText(current);$('#compareBStorage').textContent=storageText(b);const diff=(current.performance||0)-(b.performance||0);$('#compareText').textContent=diff===0?'두 제품의 내부 성능점수는 같습니다.':diff>0?`${current.name}이 내부 성능점수 기준 ${diff}점 높습니다.`:`${b.name}이 내부 성능점수 기준 ${-diff}점 높습니다.`}
function parseStorage(q,p){const raw=String(q||'');let m=raw.match(/(1|2)\s*tb/i),v=m?Number(m[1])*1024:null;if(v==null){m=raw.match(/(64|128|256|512|1024|2048)\s*(gb|기가)?/i);v=m?Number(m[1]):null}return v!=null&&(p.storage||[]).includes(v)?String(v):'all'}
async function loadLiveListings(force=false){const seq=++requestSeq,q=liveSearchQuery(),sourceText=$('#listingSourceText'),refreshBtn=$('#refreshListingsBtn');liveListings=[];liveState={loading:true,error:'',fetchedAt:'',providers:{}};if(refreshBtn){refreshBtn.disabled=true;refreshBtn.textContent='새로고침 중...'}if(sourceText)sourceText.textContent=`당근·번개장터·중고나라에서 ${filters.storage==='all'?'전체 용량':(Number(filters.storage)>=1024?Number(filters.storage)/1024+'TB':filters.storage+'GB')} 실제 매물을 불러오는 중입니다.`;renderMarket();try{const refresh=force?'&refresh=1':'';const r=await fetch(`${API_BASE}/api/live/combined?q=${encodeURIComponent(q)}&limit=36${refresh}`,{headers:{accept:'application/json'}});const data=await r.json().catch(()=>({}));if(seq!==requestSeq)return;if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);liveListings=(Array.isArray(data.listings)?data.listings:[]).filter(availableOnly);const providers=data.providers||{},failed=Object.entries(providers).filter(([,v])=>!v?.ok).map(([k])=>k),excluded=data.excluded||{},excludedCount=Object.values(excluded).reduce((s,v)=>s+(Number(v)||0),0),fresh=data.fetchedAt?new Date(data.fetchedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'',cacheNote=data.cache==='hit'?' · 캐시':data.cache==='stale'?' · 최근 정상 결과':'';liveState={loading:false,error:failed.length?`${failed.join('·')}은 현재 불러오지 못했습니다.`:'',fetchedAt:data.fetchedAt||'',providers,excluded,stale:!!data.stale};if(sourceText)sourceText.textContent=`실제 판매중 매물 ${liveListings.length}개 · ${platformCountText(liveListings)}${failed.length?` · ${failed.join('·')} 일시 오류`:''}${excludedCount?` · 관련없는 매물 ${excludedCount}개 제외`:''} · 정확한 모델만 표시${fresh?` · ${fresh} 기준`:''}${cacheNote}`;}catch(e){if(seq!==requestSeq)return;liveListings=[];liveState={loading:false,error:`${e.message||'알 수 없는 오류'} · 공개 페이지 접근이 안 되면 차단을 우회하지 않습니다.`,fetchedAt:'',providers:{}};if(sourceText)sourceText.textContent='실제 매물을 불러오지 못했습니다. 공개 페이지 차단은 우회하지 않습니다.'}finally{if(refreshBtn){refreshBtn.disabled=false;refreshBtn.textContent='매물 새로고침'}}renderMarket()}

async function search(){const q=$('#searchInput').value,p=findPhone(q);current=p;filters.storage=parseStorage(q,p);renderProduct();await loadLiveListings();window.scrollTo({top:$('#market').offsetTop-70,behavior:'smooth'})}
function suggestions(){const q=norm($('#searchInput').value),box=$('#suggestions');if(!q){box.hidden=true;return}const arr=P.filter(p=>searchableAliases(p).some(a=>a!=="iphone"&&a!=="아이폰"&&(a.includes(q)||q.includes(a)))).slice(0,8);box.innerHTML=arr.map(p=>`<button data-id="${p.id}">${p.name}</button>`).join('');box.hidden=!arr.length;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#searchInput').value=P.find(x=>x.id===b.dataset.id).name;box.hidden=true;search()})}
function renderModels(){const g=$('#modelGrid');$('#modelCount').textContent=P.length;g.innerHTML=P.map(p=>`<article class="model-card" data-id="${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy"><b>${p.name}</b><span>${p.chipset}</span></article>`).join('');g.querySelectorAll('.model-card').forEach(c=>c.onclick=async()=>{current=P.find(p=>p.id===c.dataset.id);filters.storage='all';$('#searchInput').value=current.name;renderProduct();await loadLiveListings();window.scrollTo({top:$('#market').offsetTop-70,behavior:'smooth'})})}
$('#searchBtn').onclick=search;$('#searchInput').addEventListener('input',suggestions);$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$$('[data-quick]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.quick;search()});$$('#platformFilters .chip').forEach(b=>b.onclick=()=>{filters.platform=b.dataset.platform;$$('#platformFilters .chip').forEach(x=>x.classList.toggle('active',x===b));renderMarket()});$('#priceApply').onclick=()=>{filters.min=$('#minInput').value?Number($('#minInput').value):null;filters.max=$('#maxInput').value?Number($('#maxInput').value):null;renderMarket()};$('#refreshListingsBtn').onclick=()=>loadLiveListings(true);$('#sortSelect').onchange=e=>{filters.sort=e.target.value;renderMarket()};$('#resetBtn').onclick=async()=>{const storageChanged=filters.storage!=='all';filters={platform:'all',storage:'all',min:null,max:null,sort:'cheap'};$('#minInput').value='';$('#maxInput').value='';$('#sortSelect').value='cheap';$$('#platformFilters .chip').forEach((b,i)=>b.classList.toggle('active',i===0));renderStorage();if(storageChanged)await loadLiveListings();else renderMarket()};$('#compareSelect').onchange=renderCompare;renderModels();renderProduct();loadLiveListings();
})();
