(()=>{'use strict';
const P=window.SISEBOM_PHONES||[],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],won=n=>n?Math.round(n).toLocaleString('ko-KR')+'원':'-';
let current=P.find(x=>x.id==='iphone-15')||P[0],filters={platform:'all',storage:'all',min:null,max:null,sort:'cheap'};
function norm(s){return String(s||'').toLowerCase().replace(/프로\s*맥스/g,'promax').replace(/프로/g,'pro').replace(/플러스/g,'plus').replace(/미니/g,'mini').replace(/에어/g,'air').replace(/에스\s*이/g,'se').replace(/\s+/g,'').replace(/gb/g,'').replace(/기가/g,'').replace(/-/g,'')}
function searchableAliases(p){return [p.name,...p.aliases].map(norm).filter(Boolean)}
function findPhone(q){const nq=norm(q);if(!nq)return current;let exact=P.find(p=>searchableAliases(p).some(a=>a===nq));if(exact)return exact;let best=null,bestScore=-Infinity;for(const p of P){for(const a of searchableAliases(p)){if(a==='iphone'||a==='아이폰')continue;let score=-Infinity;if(nq.includes(a))score=5000+a.length;else if(a.includes(nq))score=3000-(a.length-nq.length);if(score>bestScore){bestScore=score;best=p}}}return best||current}
function storageText(p){return p.storage.map(x=>x>=1024?(x/1024)+'TB':x+'GB').join(' · ')||'-'}
function setImage(p){const im=$('#productImage'),fb=$('#imageFallback');im.onerror=()=>{im.hidden=true;fb.hidden=false};im.src=p.image;im.hidden=false;fb.hidden=true}
function perfSub(p){const base=p.performance||50;return {daily:Math.min(100,base+3),game:Math.max(0,base-3),camera:Math.min(100,Math.max(20,base+(p.name.includes('Pro')?4:-4)))} }
function baseUsedPrice(p){const ageIndex=P.indexOf(p);let v=60000+(p.performance||50)*9000; if(p.name.includes('Pro Max'))v*=1.22;else if(p.name.includes('Pro'))v*=1.12;else if(p.name.includes('Plus'))v*=1.08;return Math.round(v/10000)*10000}
function makeListings(p){const base=baseUsedPrice(p),stor=p.storage.length?p.storage:[128],plats=['당근','번개장터','중고나라'];let arr=[];for(let i=0;i<15;i++){const s=stor[i%stor.length],storageBoost=Math.max(0,Math.log2(Math.max(64,s)/64))*25000;const swing=[-.18,-.12,-.08,-.04,0,.03,.06,.09,.13,.17,.21,.25,-.06,.02,.11][i];arr.push({platform:plats[i%3],storage:s,price:Math.max(10000,Math.round((base+storageBoost)*(1+swing)/1000)*1000),minutes:(i+1)*7,title:`${p.name} ${s>=1024?(s/1024)+'TB':s+'GB'} 중고`,region:['안양','서울','수원','인천'][i%4]})}return arr}
function filteredListings(){let a=makeListings(current);if(filters.platform!=='all')a=a.filter(x=>x.platform===filters.platform);if(filters.storage!=='all')a=a.filter(x=>String(x.storage)===String(filters.storage));if(filters.min!=null)a=a.filter(x=>x.price>=filters.min);if(filters.max!=null)a=a.filter(x=>x.price<=filters.max);if(filters.sort==='cheap')a.sort((a,b)=>a.price-b.price);if(filters.sort==='high')a.sort((a,b)=>b.price-a.price);if(filters.sort==='new')a.sort((a,b)=>a.minutes-b.minutes);return a}
function renderProduct(){const p=current,s=perfSub(p);$('#resultName').textContent=p.name;$('#productHeading').textContent=p.name+' 제품 정보';$('#specManufacturer').textContent=p.brand;$('#specChipset').textContent=p.chipset;$('#specDisplay').textContent=p.display;$('#specCamera').textContent=p.camera;$('#specCharging').textContent=p.charging;$('#specFrame').textContent=p.frame;$('#specStorage').textContent=storageText(p);$('#perfScore').textContent=p.performance;$('#dailyScore').textContent=s.daily;$('#gameScore').textContent=s.game;$('#cameraScore').textContent=s.camera;$('#dailyBar').style.width=s.daily+'%';$('#gameBar').style.width=s.game+'%';$('#cameraBar').style.width=s.camera+'%';setImage(p);document.title='시세봄 - '+p.name;renderStorage();renderCompare();}
function renderStorage(){const box=$('#storageFilters');box.innerHTML='<button class="chip '+(filters.storage==='all'?'active':'')+'" data-storage="all">전체</button>'+current.storage.map(s=>`<button class="chip ${String(filters.storage)===String(s)?'active':''}" data-storage="${s}">${s>=1024?s/1024+'TB':s+'GB'}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{filters.storage=b.dataset.storage;renderStorage();renderMarket()})}
function renderMarket(){const arr=filteredListings(),prices=arr.map(x=>x.price);$('#resultCount').textContent=arr.length;$('#visibleCount').textContent=arr.length;const mn=prices.length?Math.min(...prices):0,mx=prices.length?Math.max(...prices):0,av=prices.length?prices.reduce((a,b)=>a+b,0)/prices.length:0;$('#minPrice').textContent=won(mn);$('#avgPrice').textContent=won(av);$('#maxPrice').textContent=won(mx);$('#newPrice').textContent=current.newPrice?won(current.newPrice):'정보 없음';let score=Math.max(1,Math.min(100,Math.round(60+(current.performance-50)*.45-(av/(baseUsedPrice(current)||1)-1)*30)));$('#buyScore').textContent=score;const cls=score>=70?'green':score>=40?'yellow':'red',txt=score>=70?'구매하기 좋은 편':score>=40?'조금 더 비교':'구매 비추천';$('#scoreCircle').className='score-circle '+cls;$('#buyBadge').className='buy-badge '+cls;$('#buyBadge').textContent=txt;$('#aiHeadline').textContent=txt;$('#aiText').textContent=arr.length?`${current.name}의 현재 샘플 평균가는 ${won(av)}입니다. 용량과 플랫폼을 바꿔가며 비교해보세요.`:'조건에 맞는 매물이 없습니다.';$('#chartLabel').textContent=filters.storage==='all'?'전체 용량':(Number(filters.storage)>=1024?Number(filters.storage)/1024+'TB':filters.storage+'GB');renderBars(arr);renderListings(arr)}
function renderBars(arr){const ps=arr.map(x=>x.price);const mn=Math.min(...ps,0),mx=Math.max(...ps,1);$('#bars').innerHTML=arr.map(x=>`<div class="bar-wrap"><div class="bar" style="height:${40+((x.price-mn)/(mx-mn||1))*150}px"></div><div class="bar-label">${Math.round(x.price/10000)}만</div></div>`).join('')}
function renderListings(a){const avg=a.length?a.reduce((s,x)=>s+x.price,0)/a.length:0;$('#listingGrid').innerHTML=a.length?a.map(x=>{const d=avg?(x.price-avg)/avg*100:0;const dc=d<=-7?'good':d>=10?'bad':'';const dt=d<=-7?`평균보다 ${Math.abs(d).toFixed(0)}% 저렴`:d>=10?`평균보다 ${d.toFixed(0)}% 비쌈`:'적정 시세';return `<article class="listing"><div class="listing-top"><span class="platform-badge">${x.platform}</span><span>${x.storage>=1024?x.storage/1024+'TB':x.storage+'GB'}</span></div><h3>${x.title}</h3><b class="listing-price">${won(x.price)}</b><div class="deal ${dc}">${dt}</div><div class="listing-meta"><span>${x.region}</span><span>${x.minutes}분 전</span></div></article>`}).join(''):'<div class="muted">조건에 맞는 매물이 없습니다.</div>'}
function renderCompare(){const sel=$('#compareSelect');if(!sel.options.length)sel.innerHTML=P.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');if(sel.value===current.id)sel.value=P.find(x=>x.id!==current.id)?.id||current.id;const b=P.find(x=>x.id===sel.value)||P[0];$('#compareAName').textContent=current.name;$('#compareAChip').textContent=current.chipset;$('#compareBChip').textContent=b.chipset;$('#compareADisplay').textContent=current.display;$('#compareBDisplay').textContent=b.display;$('#compareAPerf').textContent=current.performance;$('#compareBPerf').textContent=b.performance;$('#compareAStorage').textContent=storageText(current);$('#compareBStorage').textContent=storageText(b);const diff=(current.performance||0)-(b.performance||0);$('#compareText').textContent=diff===0?'두 제품의 내부 성능점수는 같습니다.':diff>0?`${current.name}이 내부 성능점수 기준 ${diff}점 높습니다.`:`${b.name}이 내부 성능점수 기준 ${-diff}점 높습니다.`}
function parseStorage(q,p){const raw=String(q||'');let m=raw.match(/(1|2)\s*tb/i),v=m?Number(m[1])*1024:null;if(v==null){m=raw.match(/(64|128|256|512|1024|2048)\s*(gb|기가)?/i);v=m?Number(m[1]):null}return v!=null&&p.storage.includes(v)?String(v):'all'}
function search(){const q=$('#searchInput').value,p=findPhone(q);current=p;filters.storage=parseStorage(q,p);renderProduct();renderMarket();window.scrollTo({top:$('#market').offsetTop-70,behavior:'smooth'})}
function suggestions(){const q=norm($('#searchInput').value),box=$('#suggestions');if(!q){box.hidden=true;return}const arr=P.filter(p=>searchableAliases(p).some(a=>a!=="iphone"&&a!=="아이폰"&&(a.includes(q)||q.includes(a)))).slice(0,8);box.innerHTML=arr.map(p=>`<button data-id="${p.id}">${p.name}</button>`).join('');box.hidden=!arr.length;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#searchInput').value=P.find(x=>x.id===b.dataset.id).name;box.hidden=true;search()})}
function renderModels(){const g=$('#modelGrid');$('#modelCount').textContent=P.length;g.innerHTML=P.map(p=>`<article class="model-card" data-id="${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy"><b>${p.name}</b><span>${p.chipset}</span></article>`).join('');g.querySelectorAll('.model-card').forEach(c=>c.onclick=()=>{current=P.find(p=>p.id===c.dataset.id);filters.storage='all';$('#searchInput').value=current.name;renderProduct();renderMarket();window.scrollTo({top:$('#market').offsetTop-70,behavior:'smooth'})})}
$('#searchBtn').onclick=search;$('#searchInput').addEventListener('input',suggestions);$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$$('[data-quick]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.quick;search()});$$('#platformFilters .chip').forEach(b=>b.onclick=()=>{filters.platform=b.dataset.platform;$$('#platformFilters .chip').forEach(x=>x.classList.toggle('active',x===b));renderMarket()});$('#priceApply').onclick=()=>{filters.min=$('#minInput').value?Number($('#minInput').value):null;filters.max=$('#maxInput').value?Number($('#maxInput').value):null;renderMarket()};$('#sortSelect').onchange=e=>{filters.sort=e.target.value;renderMarket()};$('#resetBtn').onclick=()=>{filters={platform:'all',storage:'all',min:null,max:null,sort:'cheap'};$('#minInput').value='';$('#maxInput').value='';$('#sortSelect').value='cheap';$$('#platformFilters .chip').forEach((b,i)=>b.classList.toggle('active',i===0));renderStorage();renderMarket()};$('#compareSelect').onchange=renderCompare;renderModels();renderProduct();renderMarket();
})();
